### PR TITLE
Add component to display–only text field

### PR DESCRIPTION
**Pull request by attitude**
`DisplayTextField` is mostly similar to `TextField`, but instead of rendering `<input />`, it renders the value (or placeholder) into a div. Non-input props are transformed into `data-*` attributes that are also possible to be used by CSS to style with `content: attr(data-foo-bar)` and selectors.

**Input:**

```tsx
<>
  <TextField
    required
    labelPosition="labelLeft"
    field={'textValue'}
    label={'Text'}
    placeholder="Enter text..."
  />
  <DisplayTextField
    labelPosition="labelLeft"
    field={'textValue'}
    label={'Text'}
    placeholder="N/A"
    direction="horizontal-reverse"
  />
</>
```

**Rendered in Browser:**

Screenshot 2023-03-31 at 09 16 06

**Rendered HTML:**

```html
<div class="cui-stack view-vertical gap-small cui-field-container-body-content">
  <input class="is-required cui-text-input" placeholder="Enter text..." required="" type="text" value="">
</div>

<div class="cui-stack view-horizontal-reverse gap-small cui-field-container-body-content">
  <div data-placeholder="N/A" data-field="textValue" data-is-empty="true">N/A</div>
</div>
```

As you can see from the HTML above, it is already possible to target specific fields and add CSS based on [data-*] attributes all alone.

⚠️ This PR introduces
- a slight possibility of breaking changes on places where props were left but were not propagating correctly;
- removes deprecated `wrapLines` & `allowNewlines` from TextField.

Previously, although specified by the `SimpleRelativeSingleFieldProxy` props, the propagation of props to FieldContainer was incomplete and left duplicate efforts to omit tags to `Field*` components.

This PR fixes type of props passed from `SimpleRelativeSingleFieldProxy` to `render` method, omitting already applied props but also forwarding props that are used by the inputs, like `field`, `size` or `errors` for further inspection by the `Field*`.

- Fix: Apply missing props on `FieldContainer` in `SimpleRelativeSingleFieldProxy`
- Fix: Export Forms/Hooks and update imports (mostly renaming)
- Fix: Type of `SimpleRelativeSingleFieldProxy.render` now correctly omits consumed props.

- - -
This change is [Reviewable](https://reviewable.io/reviews/contember/interface/484)

### CODE REVIEW

**Review by attitude — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/contember/interface/484#-:-NS5ZagHA5ZiXb64VO6A:bnfp4nl)* status: 0 of 62 files reviewed, all discussions resolved (waiting on @matej21)

**Review by matej21 — CHANGES_REQUESTED** [review]
> Reviewed 61 of 61 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/interface/484)* status: all files reviewed, 3 unresolved discussions (waiting on @attitude)

___
*[`packages/admin/src/components/bindingFacade/displayFields/DisplayTextField.tsx` line 32 at r1](https://reviewable.io/reviews/contember/interface/484#-NW7ROp-8_HUd8GVeebI:-NW7ROp-8_HUd8GVeebJ:bru3jfr) ([raw file](https://github.com/contember/interface/blob/44d7dcc17ef1237f03bf7413f8b3ed10677de0df/packages/admin/src/components/bindingFacade/displayFields/DisplayTextField.tsx#L32)):*
> ```XML
> 		...props
> 	}) => {
> 		if (isDevMode()) {
> ```

`import.meta.env.DEV`
___
*[`packages/admin/src/components/bindingFacade/displayFields/DisplayTextField.tsx` line 47 at r1](https://reviewable.io/reviews/contember/interface/484#-NW7RbHj2JSUsIIE14jo:-NW7RbHj2JSUsIIE14jp:b-fltc5t) ([raw file](https://github.com/contember/interface/blob/44d7dcc17ef1237f03bf7413f8b3ed10677de0df/packages/admin/src/components/bindingFacade/displayFields/DisplayTextField.tsx#L47)):*
> ```XML
> 		return (
> 			<div
> 				data-id={id}
> ```

why data attributes?
___
*[`packages/admin/src/components/bindingFacade/fields/TextareaField.tsx` line 39 at r1](https://reviewable.io/reviews/contember/interface/484#-NW7SR69DmbPjhAe3MZ6:-NW7SR69DmbPjhAe3MZ7:b6u3p6h) ([raw file](https://github.com/contember/interface/blob/44d7dcc17ef1237f03bf7413f8b3ed10677de0df/packages/admin/src/components/bindingFacade/fields/TextareaField.tsx#L39)):*
> ```XML
> 				{...inputProps}
> 				minRows={minRows || 3}
> 				style={style}
> ```

why this change? it should be in the inputProps, i think?

**Review by attitude — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/interface/484)* status: 59 of 61 files reviewed, 3 unresolved discussions (waiting on @matej21)

___
*[`packages/admin/src/components/bindingFacade/displayFields/DisplayTextField.tsx` line 32 at r1](https://reviewable.io/reviews/contember/interface/484#-NW7ROp-8_HUd8GVeebI:-NW7fUepECAVjRJNJU6R:b-896fix) ([raw file](https://github.com/contember/interface/blob/44d7dcc17ef1237f03bf7413f8b3ed10677de0df/packages/admin/src/components/bindingFacade/displayFields/DisplayTextField.tsx#L32)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

`import.meta.env.DEV`
</blockquote></details>

Done.
___
*[`packages/admin/src/components/bindingFacade/displayFields/DisplayTextField.tsx` line 47 at r1](https://reviewable.io/reviews/contember/interface/484#-NW7RbHj2JSUsIIE14jo:-NW7dTSG7BZtAy60eeWl:b-c91dj7) ([raw file](https://github.com/contember/interface/blob/44d7dcc17ef1237f03bf7413f8b3ed10677de0df/packages/admin/src/components/bindingFacade/displayFields/DisplayTextField.tsx#L47)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

why data attributes?
</blockquote></details>

I want `className` props to be semantic name of the component and `data-*` attributes to hold the component state. `[data-*]` is targetable by CSS the same way as any `.class`.
___
*[`packages/admin/src/components/bindingFacade/fields/TextareaField.tsx` line 39 at r1](https://reviewable.io/reviews/contember/interface/484#-NW7SR69DmbPjhAe3MZ6:-NW7grLkA2tkPAnSrw7D:b3qyc3y) ([raw file](https://github.com/contember/interface/blob/44d7dcc17ef1237f03bf7413f8b3ed10677de0df/packages/admin/src/components/bindingFacade/fields/TextareaField.tsx#L39)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

why this change? it should be in the inputProps, i think?
</blockquote></details>

`style` here has different type. from `react-textarea-autosize` package

**Review by matej21 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/interface/484)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @attitude)

**Pull request merged**
