### PR TITLE
Feature (ee): deploy & serve custom admin frontend deployments

### PR DESCRIPTION
**Pull request by sitole**
Related with https://github.com/contember/engine/pull/456

- - -
This change is [Reviewable](https://reviewable.io/reviews/contember/interface/561)

### CODE REVIEW

**Review by matej21 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/interface/561)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @sitole)

___
*[`ee/admin-server/src/controllers/AssetController.ts` line 45 at r1](https://reviewable.io/reviews/contember/interface/561#-NZQ4Wkp50hfz8QG6axi:-NZQ4Wkp50hfz8QG6axj:b7bvnkw) ([raw file](https://github.com/contember/interface/blob/1bb3cab7bb0e213c9247463b11c91da703369d3b/ee/admin-server/src/controllers/AssetController.ts#L45)):*
> ```XML
> 
> 		// looks like some bad routing and domain to project group translation
> 		if (params.projectGroup === undefined) {
> ```

projectGroup can be undefined, it is a valid scenario
___
*[`ee/admin-server/src/controllers/AssetController.ts` line 85 at r1](https://reviewable.io/reviews/contember/interface/561#-NZQ7EoO8dPJoR8i7BFF:-NZQ7EoP-upAq9vK2v7v:b-xhcmxp) ([raw file](https://github.com/contember/interface/blob/1bb3cab7bb0e213c9247463b11c91da703369d3b/ee/admin-server/src/controllers/AssetController.ts#L85)):*
> ```XML
> 	private async handleAssetsFromS3(req: IncomingMessage, res: ServerResponse, path: string, params: ProjectParams): Promise<boolean> {
> 		try {
> 			const targetFile = await this.tryFiles(undefined, params.projectGroup, path)
> ```

there should be a fallback for index.html in parent directories.

If I'm trying to access /my-blog/articles/edit, it should imho check following files:

- /my-blog/articles/edit/index.html
- /my-blog/articles/index.html
- /my-blog/index.html
- /index.html

(or we could consider supporting only two last scenarios)

---

in future, we may optimize it and create a routing table during deploy.
___
*[`ee/admin-server/src/controllers/DeployController.ts` line 66 at r1](https://reviewable.io/reviews/contember/interface/561#-NZQ4fc4AcYJVijUW932:-NZQ4fc4AcYJVijUW933:b-7ji50o) ([raw file](https://github.com/contember/interface/blob/1bb3cab7bb0e213c9247463b11c91da703369d3b/ee/admin-server/src/controllers/DeployController.ts#L66)):*
> ```XML
> 		}
> 
> 		if (params.projectGroup === undefined) {
> ```

projectGroup can be undefined
___
*[`ee/admin-server/src/controllers/DeployController.ts` line 86 at r1](https://reviewable.io/reviews/contember/interface/561#-NZQ4r-47D7RxG9RSCnU:-NZQ4r-47D7RxG9RSCnV:b-tpz5i2) ([raw file](https://github.com/contember/interface/blob/1bb3cab7bb0e213c9247463b11c91da703369d3b/ee/admin-server/src/controllers/DeployController.ts#L86)):*
> ```XML
> 					{
> 						token: token,
> 						project: payload.project as string,
> ```

is the cast really necessary? it should be a string now, right?

**Comment by sitole** [comment]
todo: implement index.html fallback routing

**Review by matej21 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/contember/interface/561)* status: 8 of 9 files reviewed, 10 unresolved discussions (waiting on @sitole)

___
*[`-- commits` line 9 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzZpXnESGBwTroX44U):*
ee -> admin-server
___
*[`ee/admin-server/src/controllers/AssetController.ts` line 46 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzczqH0UFjQQR_ajgg:-NZzczqH0UFjQQR_ajgh:bwieibk) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/controllers/AssetController.ts#L46)):*
> ```XML
> 		// check and possibly switch handler to legacy mode (client does not have custom deployments with entrypoint)
> 		// for these projects we are checking access permissions
> 		if (!await this.tryCheckAdvancedStructure(params.projectGroup as string)) {
> ```

remove `as string`, the method tryCheckAdvancedStructure should support undefined
___
*[`ee/admin-server/src/controllers/AssetController.ts` line 56 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzd4KI-GKKBAP35QQ1:-NZzd4KI-GKKBAP35QQ2:b8nfsa0) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/controllers/AssetController.ts#L56)):*
> ```XML
> 
> 			// verify access permissions for projects (exclude special paths with assets)
> 			if (!specialStaticAssets.includes(<string>params.project)) {
> ```

remove `<string>` cast, add `params.project !== undefined && ...`
___
*[`ee/admin-server/src/controllers/AssetController.ts` line 59 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzdKk-3rme37bXc2fz:-NZzdKk-3rme37bXc2g-:b-9fc1r0) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/controllers/AssetController.ts#L59)):*
> ```XML
> 				const token = readAuthCookie(req)
> 
> 				if (token === null || !(await this.tenant.hasProjectAccess(token, params.project as string, params.projectGroup))) {
> ```

this can also be removed after you add !== undefined check
___
*[`ee/admin-server/src/controllers/AssetController.ts` line 134 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzds7C8Yyb2vUQH5a4:-NZzds7C8Yyb2vUQH5a5:b5enc8x) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/controllers/AssetController.ts#L134)):*
> ```XML
> 				+ '/index.html'
> 
> 			if (fallbackNeeded) {
> ```

fix the possible infinite recursion as we discussed
___
*[`ee/admin-server/src/controllers/DeployController.ts` line 43 at r3](https://reviewable.io/reviews/contember/interface/561#-NZz_-NnE40fi8kUG-K9:-NZz_-NnE40fi8kUG-KA:b-k7br42) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/controllers/DeployController.ts#L43)):*
> ```XML
> 			payload = await this.readJsonBody(req, DeployPayloadType)
> 
> 			if (payload.project) {
> ```

this is just a debug message which will be deleted, right?
___
*[`ee/admin-server/src/controllers/DeployController.ts` line 136 at r3](https://reviewable.io/reviews/contember/interface/561#-NZz__HJ4yqIPO17YytQ:-NZz__HKATpNVsGSywR5:b-tgx44m) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/controllers/DeployController.ts#L136)):*
> ```XML
> 
> 		res.writeHead(200)
> 		res.end('Deployment done')
> ```

I hope nobody relies on the "OK" message in the CI pipeline :D 
___
*[`ee/admin-server/src/services/TenantClient.ts` line 97 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzZY5j9ek_GpwzxPnN:-NZzZY5j9ek_GpwzxPnO:b-p526zk) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/services/TenantClient.ts#L97)):*
> ```XML
> 					me {
> 						permissions {
> 							canCreateProject,
> ```

canCreateProject not needed here
___
*[`ee/admin-server/src/services/TenantClient.ts` line 105 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzZdLL0MOMzGjOgZIR:-NZzZdLL0MOMzGjOgZIS:ba85vy5) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/services/TenantClient.ts#L105)):*
> ```XML
> 		})
> 
> 		if (!response.ok) {
> ```

maybe console.error? it would also be great to detect that query failed because there is no canDeployEntrypoint field, meaning you have old version of the engine

**Review by sitole — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/interface/561)* status: 8 of 9 files reviewed, 9 unresolved discussions (waiting on @matej21)

___
*[`ee/admin-server/src/controllers/AssetController.ts` line 85 at r1](https://reviewable.io/reviews/contember/interface/561#-NZQ7EoO8dPJoR8i7BFF:-NZzm6eh-vWIyX7Z9UJI:b-896fix) ([raw file](https://github.com/contember/interface/blob/1bb3cab7bb0e213c9247463b11c91da703369d3b/ee/admin-server/src/controllers/AssetController.ts#L85)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

there should be a fallback for index.html in parent directories.

If I'm trying to access /my-blog/articles/edit, it should imho check following files:

- /my-blog/articles/edit/index.html
- /my-blog/articles/index.html
- /my-blog/index.html
- /index.html

(or we could consider supporting only two last scenarios)

---

in future, we may optimize it and create a routing table during deploy.
</blockquote></details>

Done.
___
*[`ee/admin-server/src/controllers/AssetController.ts` line 46 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzczqH0UFjQQR_ajgg:-NZzmjeu31VP0htrXyD1:b-896fix) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/controllers/AssetController.ts#L46)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

remove `as string`, the method tryCheckAdvancedStructure should support undefined
</blockquote></details>

Done.
___
*[`ee/admin-server/src/controllers/AssetController.ts` line 56 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzd4KI-GKKBAP35QQ1:-NZzmjLKAJRk3L8KkMuT:b-896fix) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/controllers/AssetController.ts#L56)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

remove `<string>` cast, add `params.project !== undefined && ...`
</blockquote></details>

Done.
___
*[`ee/admin-server/src/controllers/AssetController.ts` line 59 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzdKk-3rme37bXc2fz:-NZzmkUn8q5jR8BfU4GF:b-896fix) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/controllers/AssetController.ts#L59)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

this can also be removed after you add !== undefined check
</blockquote></details>

Done.
___
*[`ee/admin-server/src/controllers/AssetController.ts` line 134 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzds7C8Yyb2vUQH5a4:-NZzm67E7Px6XA2PSN4f:b-896fix) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/controllers/AssetController.ts#L134)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

fix the possible infinite recursion as we discussed
</blockquote></details>

Done.
___
*[`ee/admin-server/src/controllers/DeployController.ts` line 43 at r3](https://reviewable.io/reviews/contember/interface/561#-NZz_-NnE40fi8kUG-K9:-NZzmCkH6kM5Y4DyxKbn:b-896fix) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/controllers/DeployController.ts#L43)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

this is just a debug message which will be deleted, right?
</blockquote></details>

Done.
___
*[`ee/admin-server/src/services/TenantClient.ts` line 97 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzZY5j9ek_GpwzxPnN:-NZznP2K65cBFm6GbvNP:b-896fix) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/services/TenantClient.ts#L97)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

canCreateProject not needed here
</blockquote></details>

Done.
___
*[`ee/admin-server/src/services/TenantClient.ts` line 105 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzZdLL0MOMzGjOgZIR:-NZzoOcmDX95aCD_H3o3:b-896fix) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/services/TenantClient.ts#L105)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

maybe console.error? it would also be great to detect that query failed because there is no canDeployEntrypoint field, meaning you have old version of the engine
</blockquote></details>

Done.

**Review by matej21 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/interface/561)* status: all files reviewed, 2 unresolved discussions (waiting on @sitole)

___
*[`ee/admin-server/src/services/TenantClient.ts` line 105 at r3](https://reviewable.io/reviews/contember/interface/561#-NZzZdLL0MOMzGjOgZIR:-N_33hWD5ejGRndhllZk:b-81nl9o) ([raw file](https://github.com/contember/interface/blob/2ce8f51f9385f07c209ff74b594744b5270032e6/ee/admin-server/src/services/TenantClient.ts#L105)):*
<details><summary><i>Previously, sitole (Jiri Sveceny) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The error is not user facing, so you should return it in a http response (so this method will return an enum sth like ok | insufficient_engine_version | other_error) 

Also, try to detect that it is a really issue with a missing field. checking that the status code === 400 should be sufficient

**Pull request closed without merging**
