### PR TITLE
Fix: Scrollable dialog

### PR DESCRIPTION
**Pull request by jonasNobile**
Scroll inside dialog when content is longer than viewport.

- - -
This change is [Reviewable](https://reviewable.io/reviews/contember/interface/411)

### CODE REVIEW

**Review by attitude — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/411)* status: all files reviewed, 1 unresolved discussion (waiting on @jonasNobile)

___
*[`packages/ui/src/styles/components/dialog.sass` line 38 at r2](https://reviewable.io/reviews/contember/admin/411#-N9lX189Dq2Mh1SvZykU:-N9lX189Dq2Mh1SvZykV:b-eam746) ([raw file](https://github.com/contember/admin/blob/120d546ed1806ff9c065e82cf0139f16f3420e21/packages/ui/src/styles/components/dialog.sass#L38)):*
> ```Sass
> 		animation: #{$cui-conf-globalPrefix}dialogIntroIn .2s .1s forwards
> 		max-height: 100%
> 		overflow-y: auto
> ```

This change seems to have no unnecessary side effects. However,... it way more safer not to have `Dialog`s direct responsibility solving overflow caused by unknown children. Moreover, the `margin: 1em` would cause children to look weirdly cropped, scrolling would hide the action buttons under the fold.

Solution would be to wrap dialog children with `DialogModal`, add `overflow: auto` rule to div with `.cui-dialog-modal-body-wrapper` class. This solution solves overflow needs but also protects important header/footer to be hidden when scrolled away.

Are you sure this change is necessary and you cannot use the `DialogModal` ui component?

**Review by jonasNobile — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/411)* status: all files reviewed, 1 unresolved discussion (waiting on @attitude)

___
*[`packages/ui/src/styles/components/dialog.sass` line 38 at r2](https://reviewable.io/reviews/contember/admin/411#-N9lX189Dq2Mh1SvZykU:-N9qRr7MBN_6bi6yh4xP:b66macf) ([raw file](https://github.com/contember/admin/blob/120d546ed1806ff9c065e82cf0139f16f3420e21/packages/ui/src/styles/components/dialog.sass#L38)):*
<details><summary><i>Previously, attitude (Martin Adamko) wrote…</i></summary><blockquote>

This change seems to have no unnecessary side effects. However,... it way more safer not to have `Dialog`s direct responsibility solving overflow caused by unknown children. Moreover, the `margin: 1em` would cause children to look weirdly cropped, scrolling would hide the action buttons under the fold.

Solution would be to wrap dialog children with `DialogModal`, add `overflow: auto` rule to div with `.cui-dialog-modal-body-wrapper` class. This solution solves overflow needs but also protects important header/footer to be hidden when scrolled away.

Are you sure this change is necessary and you cannot use the `DialogModal` ui component?
</blockquote></details>

I'm not using any UI component alone. I've discovered this bug thanks to `SelectField` createNewForm feature. Is it possible to use `DialogModal` instead of `Dialog` in `SelectField` component?

**Review by attitude — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/contember/admin/411)* status: all files reviewed, 1 unresolved discussion (waiting on @jonasNobile)

___
*[`packages/ui/src/styles/components/dialog.sass` line 38 at r2](https://reviewable.io/reviews/contember/admin/411#-N9lX189Dq2Mh1SvZykU:-N9qXAAy8hXj0tsN49jj:b-qnk3vq) ([raw file](https://github.com/contember/admin/blob/120d546ed1806ff9c065e82cf0139f16f3420e21/packages/ui/src/styles/components/dialog.sass#L38)):*
<details><summary><i>Previously, jonasNobile (Jonáš Nobile) wrote…</i></summary><blockquote>

I'm not using any UI component alone. I've discovered this bug thanks to `SelectField` createNewForm feature. Is it possible to use `DialogModal` instead of `Dialog` in `SelectField` component?
</blockquote></details>

By `SelectField` you mean the `[+]` button of select-or-create feature? Anyways I see no reason why the `DialogModal` could not be used to wrap children **inside** the `Dialog` (not instead).

Could you try wrapping the _create_ children of the dialog with `DialogModal` instead to fix your issue?

**Comment by jonasNobile** [comment]
#651

**Pull request closed without merging**
